improvements of software tools
git-svn-id: https://belle2.cc.kek.jp/svn/trunk/tools@595 b38c6c8f-bee8-465d-8448-9abe6915d496

diff --git a/addpkg b/addpkg
--- a/addpkg
+++ b/addpkg
@@ -9,12 +9,12 @@ fi
 # read arguments
 PACKAGE=$1
 if [ -d ${PACKAGE} ]; then
-  echo "The directory ${PACKAGE} already exists." 1>&2
+  echo "Error: The directory ${PACKAGE} already exists." 1>&2
   exit 1
 fi
 svn list ${BELLE2_REPOSITORY}/trunk/software/${PACKAGE} &> /dev/null
 if [ "$?" != "0" ]; then
-  echo "The package ${PACKAGE} does not exist." 1>&2
+  echo "Error: The package ${PACKAGE} does not exist." 1>&2
   exit 1
 fi
 TAG=release
@@ -23,7 +23,7 @@ if [ $# -gt 1 ]; then
   if [ "${TAG}" != "head" -a "${TAG}" != "release" ]; then
     svn list ${BELLE2_REPOSITORY}/tags/software/${PACKAGE}/${TAG} &> /dev/null
     if [ "$?" != "0" ]; then
-      echo "The tag ${TAG} does not exist." 1>&2
+      echo "Error: The tag ${TAG} does not exist." 1>&2
       exit 1
     fi
   fi
@@ -32,7 +32,7 @@ fi
 # check out package
 if [ "${TAG}" = "release" ]; then
   if [ ! -f .release ]; then
-    echo "Not in a release directory." 1>&2
+    echo "Error: Not in a release directory." 1>&2
     exit 1
   fi
   svn up ${PACKAGE}
@@ -42,8 +42,17 @@ if [ "${TAG}" = "release" ]; then
 #  else
 #    svn co ${BELLE2_REPOSITORY}/releases/software/${RELEASE}/${PACKAGE} ${PACKAGE}
 #  fi
+  if [ "$?" == "0" ]; then
+    echo "Added release version of ${PACKAGE}."
+  fi
 elif [ "${TAG}" = "head" ]; then
   svn co ${BELLE2_REPOSITORY}/trunk/${PACKAGE} ${PACKAGE}
+  if [ "$?" == "0" ]; then
+    echo "Added head version of ${PACKAGE}."
+  fi
 else
   svn co ${BELLE2_REPOSITORY}/tags/software/${PACKAGE}/${TAG} ${PACKAGE}
+  if [ "$?" == "0" ]; then
+    echo "Added tag ${TAG} of ${PACKAGE}."
+  fi
 fi
diff --git a/newrel b/newrel
--- a/newrel
+++ b/newrel
@@ -13,14 +13,14 @@ if [ $# -gt 1 ]; then
   RELEASE=$2
   svn list ${BELLE2_REPOSITORY}/releases/${RELEASE} &> /dev/null
   if [ "$?" != "0" ]; then
-    echo "The release ${RELEASE} does not exist." 1>&2
+    echo "Error: The release ${RELEASE} does not exist." 1>&2
     exit 1
   fi
 fi
 
 # create release directory and write release version to .release
 if [ -d ${DIR} ]; then
-  echo "The directory ${DIR} already exists." 1>&2
+  echo "Error: The directory ${DIR} already exists." 1>&2
   exit 1
 fi
 mkdir ${DIR}
@@ -38,3 +38,7 @@ else
   svn up SConstruct
   svn up site_scons
 fi
+
+# inform user about successful completion
+echo "New local directory created for ${RELEASE} release: ${DIR}"
+echo "-> change to the new directory and set up the environment: cd ${DIR}; setuprel"
diff --git a/tagpkg b/tagpkg
--- a/tagpkg
+++ b/tagpkg
@@ -10,19 +10,19 @@ fi
 PACKAGE=`pwd | awk -F/ '{print $NF}'`
 svn list ${BELLE2_REPOSITORY}/trunk/software/${PACKAGE} &> /dev/null
 if [ "$?" != "0" ]; then
-  echo "Not in a package directory." 1>&2
+  echo "Error: Not in a package directory." 1>&2
   exit 1
 fi
 
 # check whether we are at the head of the trunk and there are no changes
 svn info -R | grep URL | grep -v ${BELLE2_REPOSITORY}/trunk/software/${PACKAGE} &> /dev/null
 if [ "$?" = "0" ]; then
-  echo "Not at the trunk head. Use updatepkg head." 1>&2
+  echo "Error: Not at the trunk head. Use updatepkg head." 1>&2
   exit 1
 fi
 svn status -u -q | grep -v "Status against revision" &> /dev/null
 if [ "$?" = "0" ]; then
-  echo "There are modified files." 1>&2
+  echo "Error: There are modified files." 1>&2
   exit 1
 fi
 
@@ -34,8 +34,10 @@ fi
 
 # make tag and exit if tag name is explicitly given
 if [ "${TAG}" != "major" -a "${TAG}" != "minor" -a "${TAG}" != "patch" ]; then
-  echo "committing tag ${TAG} of package ${PACKAGE}"
   svn copy --parents ${BELLE2_REPOSITORY}/trunk/software/${PACKAGE} ${BELLE2_REPOSITORY}/tags/software/${PACKAGE}/${TAG} -m "tag ${TAG} of package ${PACKAGE}"
+  if [ "$?" == "0" ]; then
+    echo "Committed tag ${TAG} of ${PACKAGE}."
+  fi
   exit 0
 fi
 
@@ -75,3 +77,6 @@ fi
 TAG="v${MAJOR}-${MINOR}-${PATCH}"
 echo "committing tag ${TAG} of package ${PACKAGE}"
 svn copy --parents ${BELLE2_REPOSITORY}/trunk/software/${PACKAGE} ${BELLE2_REPOSITORY}/tags/software/${PACKAGE}/${TAG} -m "tag ${TAG} of package ${PACKAGE}"
+if [ "$?" == "0" ]; then
+  echo "Committed tag ${TAG} of ${PACKAGE}."
+fi
diff --git a/updatepkg b/updatepkg
--- a/updatepkg
+++ b/updatepkg
@@ -10,7 +10,7 @@ fi
 PACKAGE=`pwd | awk -F/ '{print $NF}'`
 svn list ${BELLE2_REPOSITORY}/trunk/software/${PACKAGE} &> /dev/null
 if [ "$?" != "0" ]; then
-  echo "Not in a package directory." 1>&2
+  echo "Error: Not in a package directory." 1>&2
   exit 1
 fi
 
@@ -21,7 +21,7 @@ if [ $# -gt 0 ]; then
   if [ "${TAG}" != "head" -a "${TAG}" != "release" ]; then
     svn list ${BELLE2_REPOSITORY}/tags/software/${PACKAGE}/${TAG} &> /dev/null
     if [ "$?" != "0" ]; then
-      echo "The tag ${TAG} does not exist." 1>&2
+      echo "Error: The tag ${TAG} does not exist." 1>&2
       exit 1
     fi
   fi
@@ -30,18 +30,30 @@ fi
 # update package
 if [ "${TAG}" = "release" ]; then
   if [ ! -f ../.release ]; then
-    echo "Not in a release directory." 1>&2
+    echo "Error: Not in a release directory." 1>&2
     exit 1
   fi
   RELEASE=`cat ../.release`
   if [ "${RELEASE}" = "head" ]; then
     svn switch ${BELLE2_REPOSITORY}/trunk/software/${PACKAGE}
+    if [ "$?" == "0" ]; then
+      echo "Updated ${PACKAGE} to head version."
+    fi
   else
     svn switch ${BELLE2_REPOSITORY}/releases/software/${RELEASE}/${PACKAGE}
+    if [ "$?" == "0" ]; then
+      echo "Updated ${PACKAGE} to release version."
+    fi
   fi
 elif [ "${TAG}" = "head" ]; then
   svn switch ${BELLE2_REPOSITORY}/trunk/software/${PACKAGE}
+  if [ "$?" == "0" ]; then
+    echo "Updated ${PACKAGE} to head version."
+  fi
 else
   svn switch ${BELLE2_REPOSITORY}/tags/software/${PACKAGE}/${TAG}
+  if [ "$?" == "0" ]; then
+    echo "Updated ${PACKAGE} to tag ${TAG}."
+  fi
 fi
 
