Fix b2anypython and handle ubuntu 20.04 better otherwise we don't get a python2 symlink, only python2.7

diff --git a/b2anypython b/b2anypython
--- a/b2anypython
+++ b/b2anypython
@@ -1,12 +1,13 @@
 #!/bin/sh
+for executable in python3 python2 python; do
+  if [ -z $PYTHON ]; then
+    PYTHON=`command -v ${executable}`
+  else
+    break
+  fi
+done
 if [ -z $PYTHON ]; then
-  PYTHON=`command -v python3`
-fi
-if [ -z $PYTHON ]; then
-  PYTHON=`command -v python2`
-fi
-if [ -z $PYTHON ]; then
-  echo "Cannot find a python executable" 1>2
+  echo "Cannot find a python executable" 1>&2
   exit 1
 fi
-$PYTHON "$@"
+$PYTHON "$"
