use astyle version in tools directory by default, thanks to Kirill
git-svn-id: https://belle2.cc.kek.jp/svn/trunk/tools@4430 b38c6c8f-bee8-465d-8448-9abe6915d496

diff --git a/fixstyle b/fixstyle
--- a/fixstyle
+++ b/fixstyle
@@ -22,12 +22,17 @@ if [ "$1" = "--help" -o "$1" = "-h" -o "$1" = "-?" ]; then
 fi
 
 # check astyle and its version
-which astyle &> /dev/null
-if [ $? != 0 ]; then
-  echo "astyle tool not found. Execute the install.sh script in the ${BELLE2_TOOLS} directory." 1>&2
-  exit 1
+ASTYLE_TOOL=${BELLE2_TOOLS}/astyle
+if [ ! -f "${ASTYLE_TOOL}" ]; then
+  echo "Warning: astyle is not found in the ${BELLE2_TOOLS} directory."
+  echo "Fixstyle will now try to use the system version."
+  ASTYLE_TOOL=$(which astyle)
+  if [ -z "${ASTYLE_TOOL}" ]; then
+    echo "astyle tool not found. Execute the install.sh script in the ${BELLE2_TOOLS} directory." 1>&2
+    exit 1
+  fi
 fi
-VERSION=`astyle -V 2>&1`
+VERSION=`${ASTYLE_TOOL} -V 2>&1`
 if [ "${VERSION}" != "Artistic Style Version 2.02" ]; then
   echo "Wrong version of astyle. Execute the install.sh script in the ${BELLE2_TOOLS} directory." 1>&2
   exit 1
@@ -38,7 +43,7 @@ BELLE2_TOOLS=${BELLE2_TOOLS:-`dirname $0`}
 
 
 # astyle command
-ASTYLE="astyle \
+ASTYLE="${ASTYLE_TOOL} \
 --indent=spaces=2 \
 --convert-tabs \
 --style=stroustrup \
