Use astyle from externals

diff --git a/fixstyle b/fixstyle
--- a/fixstyle
+++ b/fixstyle
@@ -27,19 +27,19 @@ fi
 BELLE2_TOOLS=${BELLE2_TOOLS:-`dirname $0`}
 
 # check astyle and its version
-ASTYLE_TOOL=${BELLE2_TOOLS}/astyle
+ASTYLE_TOOL=${BELLE2_EXTERNALS_DIR}/${BELLE2_ARCH}/common/bin/astyle
 if [ ! -f "${ASTYLE_TOOL}" ]; then
-  echo "Warning: astyle is not found in the ${BELLE2_TOOLS} directory."
+  echo "Warning: astyle is not found in the externals directory."
   echo "Fixstyle will now try to use the system version."
   ASTYLE_TOOL=$(which astyle)
   if [ -z "${ASTYLE_TOOL}" ]; then
-    echo "astyle tool not found. Execute the install.sh script in the ${BELLE2_TOOLS} directory." 1>&2
+    echo "Error: astyle tool not found. Setup the externals." 1>&2
     exit 1
   fi
 fi
 VERSION=`${ASTYLE_TOOL} -V 2>&1`
 if [ "${VERSION}" != "Artistic Style Version 2.05.1" ]; then
-  echo "Wrong version of astyle. Execute the install.sh script in the ${BELLE2_TOOLS} directory." 1>&2
+  echo "Error: Wrong version of astyle. Setup the latest externals version." 1>&2
   exit 1
 fi
 
