Check whether svn repository is accessible in newrel and newana
git-svn-id: https://belle2.cc.kek.jp/svn/trunk/tools@21186 b38c6c8f-bee8-465d-8448-9abe6915d496

diff --git a/newana b/newana
--- a/newana
+++ b/newana
@@ -42,6 +42,13 @@ if [ $# -gt 2 ]; then
   USERNAME=$3
 fi
 
+# check svn access
+svn list ${BELLE2_REPOSITORY} >& /dev/null
+if [ "$?" != "0" ]; then
+  echo "Error: Could not access the svn repository." 1>&2
+  exit 1
+fi
+
 # check whether this analysis directory already exists in svn
 svn list ${BELLE2_REPOSITORY}/user/${USERNAME}/${DIR} &> /dev/null
 if [ "$?" == "0" ]; then
diff --git a/newrel b/newrel
--- a/newrel
+++ b/newrel
@@ -22,6 +22,13 @@ if [ $# -lt 1 -o $# -gt 2 ]; then
   exit 1
 fi
 
+# check svn access
+svn list ${BELLE2_REPOSITORY} >& /dev/null
+if [ "$?" != "0" ]; then
+  echo "Error: Could not access the svn repository." 1>&2
+  exit 1
+fi
+
 # read arguments
 DIR=$1
 RELEASE=head
