Updated pre-commit and check_style.sh

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -13,5 +13,48 @@ if [ -z "${BELLE2_TOOLS}" ]; then
   exit 1
 fi
 
+# To check the files to be commited we need a temporary dir as there might
+# be differences between the file in the index and the file on disk
+TMPDIR=`mktemp -d`
+if [ $? -ne 0 ]; then
+  echo "Problem creating temp dir, aborting commit."
+  exit 2
+fi
+
+# Find out which files were modified
+FILES_MODIFIED=`git diff --cached --name-only`
+# Place a copy of the versions to be commited in the temp dir
+git checkout-index --prefix=${TMPDIR}/ -- ${FILES_MODIFIED}
+# Add empty file with suffix .deleted for deleted files
+for FILE in ${FILES_MODIFIED}; do
+  if [ ! -f "${TMPDIR}/${FILE}" ]; then
+    touch "${TMPDIR}/${FILE}.deleted"
+  fi
+done
+
+RESULT=0
+
 # Check the code style
-${BELLE2_TOOLS}/hooks/check_style.sh || exit 3
+${BELLE2_TOOLS}/hooks/check_style.sh ${TMPDIR}
+if [ $? -ne 0 ]; then
+  echo "=> Please run 'fixstyle' on the files listed above and 'git add' them to your commit again."
+  RESULT=3
+fi
+
+# Check the file sizes
+${BELLE2_TOOLS}/hooks/check_size.py ${TMPDIR}
+if [ $? -ne 0 ]; then
+  RESULT=4
+fi
+
+# Clean up the temp dir
+rm -r ${TMPDIR}
+
+# Return check result
+if [ $RESULT -ne 0 ]; then
+  echo "*** Commit aborted ***"
+fi
+
+exit 1
+
+exit $RESULT
