Check for externals setup in pre-commit hook

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -6,10 +6,17 @@ if git diff --cached --quiet; then
   exit 0
 fi
 
-# Check the tools setup
+# Check the tools setup (needed for checkstyle)
 if [ -z "${BELLE2_TOOLS}" ]; then
   echo "The tools are not set up, aborting commit."
   echo "Source tools/setup_belle2 to set up the tools."
+  exit 1
+fi
+
+# Check the externals setup (needed for astyle and pep8)
+if [ -z "${BELLE2_EXTERNALS_DIR}" ]; then
+  echo "The externals are not set up, aborting commit."
+  echo "Set up a release with 'setuprel' or the extenals with 'setupext'."
   exit 1
 fi
 
